sudo: false
language: java
node_js:
  - "6"
jdk:
  - oraclejdk8
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport    
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coveralls
