sudo: false
language: java
node_js:
  - "6"
jdk:
  - oraclejdk8
env:
  - CXX=g++-4.8
before_cache:
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
  - node_modules
  - build/nodejs
  - build/npm
  - build/yarn
  - .gradle/caches/
  - .gradle/wrapper/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
